import {useEffect, useMemo, useState} from 'react';
import {Bell, ChevronRight, Globe2, Home, Info as InfoIcon, Map, ShieldAlert, Waves} from 'lucide-react';

type Id='gwangalli'|'haeundae'|'songjeong'|'dadaepo'; type Risk='SAFE'|'MODERATE'|'CAUTION'|'DANGER'; type DataRisk='LOW'|'MEDIUM'|'HIGH'|'VERY_HIGH'; type Page='home'|'map'|'alerts'|'info';
type Beach={id:Id; temp:number; wave:number; rip:DataRisk;jelly:DataRisk;wind:number;time:string|null;lat:number;lng:number};
const beaches:Beach[]=[{id:'gwangalli',temp:27.4,wave:.6,rip:'HIGH',jelly:'HIGH',wind:3.2,time:'09:00 ~ 11:00',lat:35.153,lng:129.119},{id:'haeundae',temp:26.8,wave:.8,rip:'MEDIUM',jelly:'MEDIUM',wind:4.1,time:'08:00 ~ 10:00',lat:35.158,lng:129.160},{id:'songjeong',temp:25.9,wave:.4,rip:'LOW',jelly:'LOW',wind:2.5,time:'09:00 ~ 12:00',lat:35.179,lng:129.200},{id:'dadaepo',temp:28.1,wave:1.4,rip:'VERY_HIGH',jelly:'MEDIUM',wind:6.8,time:null,lat:35.048,lng:128.966}];
const names:Record<Id,Record<string,string>>={gwangalli:{ko:'광안리 해수욕장',en:'Gwangalli Beach','zh-CN':'广安里海水浴场',ja:'広安里海水浴場'},haeundae:{ko:'해운대 해수욕장',en:'Haeundae Beach','zh-CN':'海云台海水浴场',ja:'海雲台海水浴場'},songjeong:{ko:'송정 해수욕장',en:'Songjeong Beach','zh-CN':'松亭海水浴场',ja:'松亭海水浴場'},dadaepo:{ko:'다대포 해수욕장',en:'Dadaepo Beach','zh-CN':'多大浦海水浴场',ja:'多大浦海水浴場'}};
const copy:Record<string,any>={ko:{app:'부산 바다안전 AI',sub:'바다 위험을 분석하고, 안전한 해수욕을 안내합니다.',home:'홈',map:'지도',alerts:'알림',info:'정보',detail:'상세 정보 보기',current:'현재 상태',hourly:'시간별 예측',weekly:'7일 예측',overall:'종합 위험도',recommended:'안전 수영 시간대 추천',danger:'현재는 입수를 권장하지 않습니다. 현장 안전요원의 안내를 확인하세요.',mock:'이 서비스의 데이터는 현재 시연용 Mock Data이며 실제 해양 안전정보가 아닙니다.'},en:{app:'Busan Sea Safety AI',sub:'Understand sea risks and plan a safer swim.',home:'Home',map:'Map',alerts:'Alerts',info:'Info',detail:'View details',current:'Current',hourly:'Hourly Forecast',weekly:'7-Day Forecast',overall:'Overall Risk',recommended:'Recommended Safe Time',danger:'Swimming is not recommended. Follow local safety staff instructions.',mock:'This service uses demonstration mock data, not live marine safety data.'},'zh-CN':{app:'釜山海洋安全 AI',sub:'分析海洋风险，帮助您安全游泳。',home:'首页',map:'地图',alerts:'提醒',info:'信息',detail:'查看详情',current:'当前状态',hourly:'每小时预报',weekly:'7天预报',overall:'综合风险',recommended:'推荐安全时段',danger:'目前不建议下水，请遵从现场安全人员指示。',mock:'本服务采用演示模拟数据，并非实时海洋安全信息。'},ja:{app:'釜山海の安全 AI',sub:'海の危険を分析し、安全な海水浴を案内します。',home:'ホーム',map:'地図',alerts:'お知らせ',info:'情報',detail:'詳細を見る',current:'現在の状況',hourly:'時間別予報',weekly:'7日間予報',overall:'総合リスク',recommended:'安全な遊泳時間のおすすめ',danger:'現在は遊泳をおすすめしません。現地の安全員の案内に従ってください。',mock:'このサービスはデモ用のモックデータを使用しています。'}};
const score=(b:Beach)=>({LOW:0,MEDIUM:15,HIGH:30,VERY_HIGH:45}[b.rip]+{LOW:0,MEDIUM:7,HIGH:14,VERY_HIGH:20}[b.jelly]+(b.wave<.5?0:b.wave<1?5:b.wave<1.5?12:20)+(b.wind<3?0:b.wind<5?4:b.wind<8?10:18)+(b.temp<18||b.temp>30?5:0));
const risk=(b:Beach):Risk=>{const s=score(b);return s<15?'SAFE':s<30?'MODERATE':s<50?'CAUTION':'DANGER'};
const riskKo:Record<Risk,string>={SAFE:'안전',MODERATE:'보통',CAUTION:'주의',DANGER:'위험'};
function Badge({r}:{r:Risk}){return <span className={'badge '+r}><ShieldAlert size={15}/>{riskKo[r]} · {r}</span>}
function App(){const[lang,setLang]=useState(localStorage.getItem('busan-lang')||navigator.language.slice(0,2)==='en'?'en':'ko');const[page,setPage]=useState<Page>('home');const[selected,setSelected]=useState<Id>('gwangalli');const[detail,setDetail]=useState(false);const[tab,setTab]=useState<'current'|'hourly'|'weekly'>('current');const t=copy[lang]||copy.ko;const beach=beaches.find(b=>b.id===selected)!;const r=risk(beach);useEffect(()=>{localStorage.setItem('busan-lang',lang);document.documentElement.lang=lang;document.title=t.app},[lang,t.app]); const nav=(p:Page)=>{setPage(p);setDetail(false)};
return <main><header><div className="brand"><span className="logo"><Waves/></span><div><strong>{t.app}</strong><small>{t.sub}</small></div></div><div className="tools"><label><Globe2 size={17}/><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value)}><option value="ko">한국어</option><option value="en">English</option><option value="zh-CN">中文</option><option value="ja">日本語</option></select></label><button aria-label="Notifications"><Bell size={19}/></button></div></header>
{page==='home'&&(!detail?<HomePage beach={beach} r={r} t={t} lang={lang} onDetail={()=>setDetail(true)} onSelect={setSelected}/>:<Detail beach={beach} r={r} t={t} tab={tab} setTab={setTab}/>) }{page==='map'&&<MapPage t={t} lang={lang} onSelect={id=>{setSelected(id);setPage('home');setDetail(true)}}/>}{page==='alerts'&&<Alerts t={t}/>} {page==='info'&&<InfoPage t={t}/>}<footer>{t.mock}</footer><nav>{([{p:'home',i:Home},{p:'map',i:Map},{p:'alerts',i:Bell},{p:'info',i:InfoIcon}] as const).map(({p,i:Icon})=><button className={page===p?'active':''} onClick={()=>nav(p)} key={p}><Icon size={20}/><span>{t[p]}</span></button>)}</nav></main>}
function HomePage({beach,r,t,lang,onDetail,onSelect}:{beach:Beach;r:Risk;t:any;lang:string;onDetail:()=>void;onSelect:(id:Id)=>void}){return <section className="content"><div className="eyebrow">TODAY · BUSAN BEACHES</div><article className="hero"><div><p>{names[beach.id][lang]||names[beach.id].ko}</p><Badge r={r}/><h1>{r==='DANGER'?t.danger:'현재 바다 상태를 확인하고 안전하게 이용하세요.'}</h1><button className="primary" onClick={onDetail}>{t.detail}<ChevronRight size={18}/></button></div><div className="sun">☀<Waves/></div></article><h2>부산 해수욕장 현황</h2><div className="beach-list">{beaches.map(b=><button onClick={()=>onSelect(b.id)} className={'beach '+(b.id===beach.id?'selected':'')} key={b.id}><span><strong>{names[b.id][lang]||names[b.id].ko}</strong><small>수온 {b.temp}°C · 파고 {b.wave}m</small></span><Badge r={risk(b)}/><ChevronRight size={18}/></button>)}</div></section>}
function Detail({beach,r,t,tab,setTab}:{beach:Beach;r:Risk;t:any;tab:string;setTab:(t:any)=>void}){const metrics=[['🌡️','수온',`${beach.temp}°C`,'평년보다 약간 높은 수온입니다.'],['🌊','파도 높이',`${beach.wave} m`,beach.wave<1?'파도가 비교적 잔잔합니다.':'파도에 주의가 필요합니다.'],['↔️','이안류 위험',beach.rip,'발생 가능성을 계속 확인하세요.'],['🪼','해파리 출현',beach.jelly,'피부 노출에 주의하세요.'],['💨','풍속',`${beach.wind} m/s`,'해안 바람이 불고 있습니다.']];return <section className="content"><button className="back" onClick={()=>history.back()}>← 홈으로</button><h1>{names[beach.id].ko}</h1><div className="tabs">{[['current',t.current],['hourly',t.hourly],['weekly',t.weekly]].map(([id,label])=><button className={tab===id?'on':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>{tab==='current'&&<><article className={'overall '+r}><span>{t.overall}</span><Badge r={r}/><h2>{r==='DANGER'?t.danger:'입수 전 주의가 필요합니다.'}</h2></article><div className="metrics">{metrics.map(m=><article className="metric" key={m[1]}><span>{m[0]}</span><small>{m[1]}</small><strong>{m[2]}</strong><p>{m[3]}</p></article>)}</div>{r==='DANGER'?<article className="notice dangerNotice">{t.danger}</article>:<article className="notice"><strong>{t.recommended}</strong><p>오늘은 <b>{beach.time}</b> 사이가 상대적으로 안전할 것으로 예상됩니다.</p><small>Mock Data 기반 안내</small></article>}</>}{tab==='hourly'&&<Chart beach={beach}/>} {tab==='weekly'&&<Weekly/>}</section>}
function Chart({beach}:{beach:Beach}){const values=[25,30,35,42,48,54,48,40];return <div className="forecast"><h2>오늘의 시간별 예측</h2><div className="chart">{values.map((v,i)=><div key={i}><i style={{height:`${v}%`}}></i><span>{9+i}:00</span></div>)}</div><p>위험 점수 · 파고 · 풍속을 종합한 Mock Forecast</p><div className="metricline">파고 {beach.wave}m · 풍속 {beach.wind}m/s</div></div>}
function Weekly(){return <div className="weekly">{['오늘','목','금','토','일','월','화'].map((d,i)=><article key={d}><small>{d}</small><strong>{['주의','보통','안전','안전','보통','주의','주의'][i]}</strong><span>파고 {(0.4+i*.1).toFixed(1)}m</span><span>풍속 {2+i}m/s</span></article>)}</div>}
function MapPage({t,lang,onSelect}:{t:any;lang:string;onSelect:(id:Id)=>void}){return <section className="content"><h1>부산 해수욕장 지도</h1><p className="muted">Mock location · OpenStreetMap 연동 전 데모 지도</p><div className="mapbox"><div className="water">BUSAN COAST</div>{beaches.map((b,i)=><button onClick={()=>onSelect(b.id)} className={'pin '+risk(b)} style={{left:`${20+i*21}%`,top:`${55-(i%2)*24}%`}} key={b.id}><span></span><b>{names[b.id][lang]||names[b.id].ko}</b><Badge r={risk(b)}/></button>)}</div><p>{t.detail} 버튼처럼 마커를 눌러 해당 해수욕장 정보를 확인하세요.</p></section>}
function Alerts({t}:{t:any}){const[a,setA]=useState('all');const items=[['risk','광안리 해수욕장 이안류 위험 증가','현재 이안류 발생 가능성이 높습니다. 입수 전 주의해주세요.','CAUTION'],['risk','다대포 해수욕장 입수 위험','파고와 이안류 위험이 높습니다.','DANGER'],['safety','송정 해수욕장 안전 안내','현재 바다 상태가 비교적 좋습니다.','SAFE']];return <section className="content"><h1>{t.alerts}</h1><div className="tabs"><button className={a==='all'?'on':''} onClick={()=>setA('all')}>전체</button><button className={a==='risk'?'on':''} onClick={()=>setA('risk')}>위험 알림</button><button className={a==='safety'?'on':''} onClick={()=>setA('safety')}>안전 정보</button></div>{items.filter(x=>a==='all'||x[0]===a).map(x=><article className="alert" key={x[1]}><Badge r={x[3] as Risk}/><h2>{x[1]}</h2><p>{x[2]}</p><small>오늘 09:30</small></article>)}</section>}
function InfoPage({t}:{t:any}){return <section className="content info"><h1>{t.app}</h1><h2>서비스 소개</h2><p>부산 주요 해수욕장의 수온, 파도, 이안류, 해파리, 풍속 정보를 바탕으로 안전 상태를 알기 쉽게 보여주는 다국어 데모 서비스입니다.</p><h2>위험도 분석 기준</h2><p>이안류에 가장 높은 가중치를 부여하고 해파리, 파고, 풍속, 극단적 수온을 합산합니다. 점수는 안전 · 보통 · 주의 · 위험으로 자동 변환됩니다.</p><article className="notice"><strong>안전 안내</strong><p>{t.mock} 실제 해수욕 시에는 기상청·해양수산부와 현장 안전요원의 공식 안내를 반드시 확인하세요.</p></article></section>}
export default App;
